"use strict"

//css
import "./styles/form/form.css"
import "./styles/form/input.css"
import "./styles/btn.css"
import "./styles/global.css"
import "./styles/header.css"
import "./styles/logo.css"
import "./styles/modal.css"
import "./styles/schedules.css"
import "./styles/utility.css"

//js
import "./modules/form/open-modal.js"
import "./libs/day.js"
import "./modules/page-load.js"
import "./services/api-config.js"
import "./services/new-schedule.js"
import "./modules/form/submit.js"
import "./modules/schedules/show-schedules.js"
import "./modules/schedules/load.js"
import "./modules/date-change.js"
import "./services/is-same-hour.js"
import "./services/schedule-cancel.js"
import "./modules/schedules/delete-schedule.js"